name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t vasilijed/counter-backend:${{ github.sha }} .

    - name: Set up K3D Kubernetes
      shell: cmd
      run: |
        k3d cluster delete ci-cluster 2>nul
        k3d cluster create ci-cluster --agents 1 --wait
        k3d kubeconfig get ci-cluster > %USERPROFILE%\.kube\config

    - name: Deploy backend
      shell: cmd
      run: |
        kubectl create namespace ${{ github.ref_name }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/ -n ${{ github.ref_name }}
        kubectl rollout restart deployment/counter-backend-deployment -n ${{ github.ref_name }}

    - name: Verify deployment
      shell: cmd
      run: |
        kubectl rollout status deployment/counter-backend-deployment -n ${{ github.ref_name }} --timeout=120s