name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t vasilijed/counter-backend:${{ github.sha }} .

    - name: Restart backend deployment
      shell: cmd
      run: |
        kubectl rollout restart deployment/counter-backend-deployment -n ${{ github.ref_name }}

    - name: Verify deployment
      shell: cmd
      run: |
        kubectl rollout status deployment/counter-backend-deployment -n ${{ github.ref_name }} --timeout=120s