name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Backend Docker image
      run: |
        docker build -t counter-backend:${{ github.sha }} .

    - name: Set up Minikube
      uses: medyagh/setup-minikube@v1

    - name: Load backend image to Minikube
      run: |
        minikube image load counter-backend:${{ github.sha }}

    - name: Deploy backend to namespace
      run: |
        kubectl create namespace ${{ github.ref_name }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/ -n ${{ github.ref_name }}
        kubectl set image deployment/counter-backend-deployment \
          backend-container=counter-backend:${{ github.sha }} -n ${{ github.ref_name }} || true
        
    - name: Verify backend deployment
      run: |
        kubectl rollout status deployment/counter-backend-deployment -n ${{ github.ref_name }} --timeout=300s
        echo "Backend deployed to ${{ github.ref_name }} namespace"