name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 3
    defaults:
      run:
        working-directory: task1\backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: dojcinovvasilje/CounterApp_API
        

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t vasilijed/counter-backend:${{ github.sha }} .
        docker tag vasilijed/counter-backend:${{ github.sha }} vasilijed/counter-backend:latest
      working-directory: task1/backend

    - name: Push Docker image
      shell: cmd
      run: |
        docker push vasilijed/counter-backend:${{ github.sha }}
        docker push vasilijed/counter-backend:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Debug - Check environment
      run: |
        echo "Current directory:"
        pwd
        echo "Files in directory:"
        dir
        echo "Terraform version:"
        terraform version
        echo "Kubernetes nodes:"
        kubectl get nodes
        echo "Docker images:"
        docker images

    - name: Deploy with Terraform  
      run: |
        terraform init
        terraform apply -auto-approve
        working-directory: task1/backend