name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 4
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t vasilijed/counter-backend:${{ github.sha }} .

    - name: Configure kubeconfig
      shell: cmd
      run: |
        echo KUBECONFIG=%USERPROFILE%\.kube\config>> %GITHUB_ENV%

    - name: Apply or restart deployment
      shell: cmd
      run: |
        set KUBECONFIG=%USERPROFILE%\.kube\config
        kubectl create namespace %GITHUB_REF_NAME% --dry-run=client -o yaml | kubectl apply -f - --validate=false --insecure-skip-tls-verify=true
        kubectl apply -f k8s/ -n %GITHUB_REF_NAME% --validate=false --insecure-skip-tls-verify=true
        kubectl rollout restart deployment/counter-backend-deployment -n %GITHUB_REF_NAME% --insecure-skip-tls-verify=true


    - name: Verify deployment
      shell: cmd
      run: |
        kubectl rollout status deployment/counter-backend-deployment -n %GITHUB_REF_NAME% --timeout=120s
