name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push to Docker Hub
      shell: cmd
      run: |
        docker build -t vasilijed/counter-backend:${{ github.sha }} .
        echo %DOCKER_PASSWORD% | docker login -u %DOCKER_USERNAME% --password-stdin
        docker push vasilijed/counter-backend:${{ github.sha }}

    - name: Use existing K3D cluster
      shell: cmd
      run: |
        k3d kubeconfig get ci-cluster > %USERPROFILE%\.kube\config

    - name: Restart backend deployment
      shell: cmd
      run: |
        kubectl rollout restart deployment/counter-backend-deployment -n ${{ github.ref_name }}

    - name: Verify deployment
      shell: cmd
      run: |
        kubectl rollout status deployment/counter-backend-deployment -n ${{ github.ref_name }} --timeout=120s